### ISSUE TITLE
Unable to build on FreeBSDv11.2 Release

### ISSUE THREAD

**Issue by frankhucek** [Bitcoin-ABC/bitcoin-abc#258]
After following the instructions for building on FreeBSD in `doc/build-unix.md`, gmake fails with the following error:
```
/usr/local/bin/ld: warning: libcrypto.so.8, needed by /usr/local/lib/libevent_pthreads.so, may conflict with libcrypto.so.9
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `SetupEnvironment()':                                            
/home/user/Code/bitcoin-abc/build-aux/src/.././../src/util.cpp:617: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'                                                                                                     
/home/user/Code/bitcoin-abc/build-aux/src/.././../src/util.cpp:618: undefined reference to `boost::filesystem::path::imbue(std::locale const&)'                                                                                                     
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::getline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':                              
/usr/local/include/boost/program_options/detail/config_file.hpp:171: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'                            
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::basic_config_file_iterator(std::istream&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool)':                            
/usr/local/include/boost/program_options/detail/config_file.hpp:155: undefined reference to `boost::program_options::detail::common_config_file_iterator::common_config_file_iterator(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool)'             
collect2: error: ld returned 1 exit status                                                                                
gmake[2]: *** [Makefile:4198: bitcoind] Error 1                                                                           
gmake[2]: Leaving directory '/home/user/Code/bitcoin-abc/build-aux/src'                                                  
gmake[1]: *** [Makefile:10520: all-recursive] Error 1                                                                     
gmake[1]: Leaving directory '/home/user/Code/bitcoin-abc/build-aux/src'                                                  
gmake: *** [Makefile:720: all-recursive] Error 1
```
I have ensured that `boost` is installed and working.
cwd: `bitcoin-abc/build-aux` (used this as current working directory because configure was failing)
The commands I ran to produce this error were
`$ ./../autogen.sh`
`$ ./../configure --without-gui --without-miniupnpc --disable-wallet`
Both of these commands succeed. I follow them with `$ gmake` and each time the build error occurs.

### Machine specs:
- OS: Freebsd 11.2
- CPU: Intel Xeon E3-1245
- RAM: 16GB

**Comment by ViralTaco** [comment]
Oh the joy of unspecified behavior. (Posix this time, not c++)
Ok it's a linker error. (I know, I'm observant). Very easy fix (dev side): stop using boost. 
I recommend you clean your previous install. Maybe even kill the thread? 😐 
It's just the first line of the error message. 
Then it's a matter of using the right version of clang (you can use g++ but then you you can't cry), using the right version of c++, boost (which you need to link properly), make sure your locale is set up properly. Then install another OS because it's really not helping.
